# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SourceryExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SourceryExample
  pod 'Sourcery'
  
  target 'SourceryExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.7.2'
  end

  target 'SourceryExampleUITests' do
    # Pods for testing
  end

end
